
[project]
description = ""
name = "porringer"

license = { text = "MIT" }

authors = [{ name = "Synodic Software", email = "contact@synodic.software" }]
readme = "README.md"

dynamic = ["version"]

requires-python = ">=3.13"

dependencies = [
  "typer[all]>=0.15.2",
  "pydantic>=2.11.3",
  "platformdirs>=4.3.7",
  "userpath>=1.9.2",
  "packaging>=24.2",
]

[project.urls]
homepage = "https://github.com/Synodic-Software/Porringer"
repository = "https://github.com/Synodic-Software/Porringer"

[dependency-groups]
lint = ["mypy>=1.15.0", "ruff>=0.11.5"]
test = ["pytest>=8.3.5", "pytest-cov>=6.1.1", "pytest-mock>=3.14.0"]

[project.entry-points."porringer.environment"]
pip = "porringer.plugin.pip.plugin:PipEnvironment"
pipx = "porringer.plugin.pipx.plugin:PipxEnvironment"
winget = "porringer.plugin.winget.plugin:WingetEnvironment"

[project.scripts]
porringer = "porringer.console.entry:app"

[tool.pytest.ini_options]
log_cli = true
testpaths = ["tests"]

[tool.mypy]
exclude = "__pypackages__"
plugins = ["pydantic.mypy"]
strict = true

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = ["D206", "D300", "D415", "E111", "E114", "E117"]
select = [
  "D",   # pydocstyle
  "F",   # Pyflakes
  "I",   # isort
  "PL",  # pylint
  "UP",  # pyupgrade
  "E",   # pycodestyle
  "B",   # flake8-bugbear
  "SIM", # flake8-simplify
  "PT",  # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm]
plugins = ["-e file:///${PROJECT_ROOT}"]

[tool.pdm.options]
update = ["--update-all"]

[tool.pdm.version]
source = "scm"

[tool.pdm.scripts]
analyze = { shell = "ruff check porringer tests" }
format = { shell = "ruff format" }
lint = { composite = ["analyze", "format", "type-check"] }
test = { shell = "pytest --cov=porringer --verbose tests" }
type-check = { shell = "mypy ." }

[build-system]
build-backend = "pdm.backend"
requires = ["pdm.backend"]
