name: Update Python Development Release
on:
  push: 
    branches: 
      - '**'

jobs:
  publish_release:
    if: github.repository_owner == 'synodic'
    uses: synodic/.github/.github/workflows/python-merge.yml@stable
    with:
      repository_url: https://upload.pypi.org/legacy/
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
